### PR TITLE
Intensity Statistic and Exodus output

### PR DESCRIPTION
**Pull request by mperrinel**
@jjwilke 

Created a new statistic intensity and a new Exodus output with a first implementation using vtk.
VTK can be enabled as a new options : 

- --with-vtk=%ThePathThatContainsAnInstallationOfVTK
- --enable-vtk=%TheVersionOfVTK%

### CODE REVIEW

**Review by jjwilke — APPROVED** [review]
Okay to test

**Comment by feldergast** [comment]
This branch will need to be updated to include the changes in the last couple PRs before it will pass testing again.

**Comment by feldergast** [comment]
Setting WIP label until branch is updated with most recent changes to avoid having the autotester continue to test.  Remove the WIP label once it is updated.

**Review by jjwilke — APPROVED** [review]
okay to test

**Comment by feldergast** [comment]
Closing for now.  Will revisit at a future date.

**Pull request closed without merging**
