### PR TITLE
Remove dependency on boost::program_options

### PR DESCRIPTION
**Pull request by bjmoor**
* Remove dependency on boost::program_options.
* Add a '--debug/-d' flag to sst-info to enable error reporting from the classloader.  #156 
* Remove all refences to boost::serialization in the build system.  It isn't referenced in code.

### CODE REVIEW

**Comment by allevin** [comment]
This core is failing to build on autotester 

I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I../../../src/sst/core/libltdl -I../../.. -I../../.. -I../../../src -I../../../src   -g -O2 -std=c++1y -D__STDC_FORMAT_MACROS -MT configGraph.o -MD -MP -MF $depbase.Tpo -c -o configGraph.o configGraph.cc &&\
	mv -f $depbase.Tpo $depbase.Po
config.cc:25:10: fatal error: 'termio.h' file not found
#include <termio.h>
         ^

**Comment by bjmoor** [comment]
@nmhamster A grep of the codebase shows no references to program_options.   scheduler pulls in other boost things (tokenizer, thread, filesystem, algorithm/string), but I don't believe it uses program_options.

**Comment by allevin** [comment]
Closing this Pull Request to perform more testing.  Current version of source branch is causing many  lockups of SST thereby causing autotester to timeout.  Will repopen or recreate Pull Request when issues have been resolved.

**Comment by bjmoor** [comment]
Lockups of SST were due to a missing 'stopAtCyle' - (in addition to 'stop-at').  Latest commit should fix this.

**Pull request merged**
