### PR TITLE
Add interactive sst-info

### PR DESCRIPTION
**Pull request by bliu1013**
Adding first version of interactive SST-info, activated using flag `-i` / `--interactive`

### CODE REVIEW

**Comment by bliu1013** [comment]
Not sure why it's duplicating commits here, I ran:

`git fetch upstream`
`git rebase upstream/devel`
`git push --force`

Any suggestions on how to fix this?

**Review by feldergast — CHANGES_REQUESTED** [review]
Generally things look good, but we need to bracket all the new code in #ifdefs that ensure that ncurses is installed.  That way if there's a machine that doesn't have it installed for some reason, sst will still compile.

**Comment by bliu1013** [comment]
@feldergast I've added in the #ifdefs and the error messages from the other PR. However, do you know if the code would actually configure and compile correctly without curses due to the  changed code in `configure.ac`? I'm not too familiar with how autotools works, but it seems to me that either the AX_WITH_CURSES macro or the linker flag could throw an error anyways:

```
AX_WITH_CURSES
if test "x$ax_cv_ncursesw" != xyes && test "x$ax_cv_ncurses" != xyes; then
    AC_MSG_ERROR([requires either NcursesW or Ncurses library])
fi
LDFLAGS="$LDFLAGS -lncurses"
```

**Comment by bliu1013** [comment]
Going to go ahead and close this PR and try again

**Pull request closed without merging**
