### PR TITLE
Add Min and Max outputs for Accumulator statistics

### PR DESCRIPTION
**Pull request by nmhamster**
Addresses issue #343.

### CODE REVIEW

**Comment by allevin** [comment]
@jpvandy Are these tests failing because of the golden data has not been updated?

**Comment by allevin** [comment]
@nmhamster 

I think this is failing for 2 reasons.  

1) The extra fields in the output file 

2) Strange data on third line of output see below...



```
John,

If this is related to PR 345, then it looks like the new data on the third line (Min.u64 = 18446744073709551615) seems odd. @Hammond, Simon David do you agree?

-- 
Aaron

From: "Vandyke, John P" <jpvandy@sandia.gov>
 
NOT READY TO JUST CREATE NEW REFERENCE FILE
          -------
test_cassini_prefetcher_none  nt=1
Simulation is complete, simulated time: 11.5218 ms
Output does not match Reference File
3,134c3,134
<  l1cache.TotalEventsReceived : Accumulator : Sum.u64 = 112500; SumSQ.u64 = 112500; Count.u64 = 112500;
<  l1cache.TotalEventsReplayed : Accumulator : Sum.u64 = 80713; SumSQ.u64 = 80713; Count.u64 = 80713;
<  l1cache.TotalNoncacheableEventsReceived : Accumulator : Sum.u64 = 0; SumSQ.u64 = 0; Count.u64 = 0;
<  l1cache.CacheHits : Accumulator : Sum.u64 = 87500; SumSQ.u64 = 87500; Count.u64 = 87500;
 
---
>  l1cache.TotalEventsReceived : Accumulator : Sum.u64 = 112500; SumSQ.u64 = 112500; Count.u64 = 112500; Min.u64 = 1; Max.u64 = 1;
>  l1cache.TotalEventsReplayed : Accumulator : Sum.u64 = 80713; SumSQ.u64 = 80713; Count.u64 = 80713; Min.u64 = 1; Max.u64 = 1;
>  l1cache.TotalNoncacheableEventsReceived : Accumulator : Sum.u64 = 0; SumSQ.u64 = 0; Count.u64 = 0; Min.u64 = 18446744073709551615; Max.u64 = 0;
>  l1cache.CacheHits : Accumulator : Sum.u64 = 87500; SumSQ.u64 = 87500; Count.u64 = 87500; Min.u64 = 1; Max.u64 = 1;
```

**Comment by nmhamster** [comment]
@alevine947 - the large weird number is correct. In the eventuality of a count of zero items being provided, the system defaults to output the max of the data type (for the min value) and the min of the value for the max. Let me know if you think we should do something else.

**Comment by allevin** [comment]
@nmhamster Hmm, I see what you are saying, its just odd.  I feel it should really show 0 for both since there was no data at all.  Having the max for the data type infers that some data was collected when in fact nothing came in.  Its confusing...

**Comment by allevin** [comment]
@jpvandy Si's change will affect the output, so you might need to re-run to get new golden data.

**Comment by allevin** [comment]
@nmhamster Turning on WIP to prevent the autotester from flogging the dead horse...

**Comment by allevin** [comment]
This Branch was tested manually on 3/20/2018 on 3 separate Jenkins runs:

https://jenkins-srn.sandia.gov/view/SST/job/SST__AnyBranch_Combo_Tester_Ubuntu_16.04/29/
https://jenkins-srn.sandia.gov/view/SST/job/SST__AnyBranch_Combo_Tester_sst-test/290/
https://jenkins-srn.sandia.gov/view/SST/job/SST__AnyBranch_Combo_Tester_ElCapitan/163/

These AnyBranch tests were against branches:
sst-core/stat-add-minmax
sst-elements/JohnRef

Due to the nature of the PR autotester being able to test only a modified single branch at a time, we must use the AnyBranch manual Testing method for situations like this when 2 branches in separate repos must change concurrently.  

All 3 Jobs mentioned above passed, so this PR will be manually merged.

**Pull request merged**
