### PR TITLE
Unify python

### PR DESCRIPTION
**Pull request by jjwilke**
* Fixes build issues with Python <= 3.7

### CODE REVIEW

**Comment by jjwilke** [comment]
@allevin Are we not testing Python 3.6 or 3.7? Not sure how the original PR passed. PR #540 only worked on 3.8.

**Comment by allevin** [comment]
I will have to investigate.  Py3 testing on platforms was targeted to whatever was installed on the machine at the time.  We did not do a matrix of tests.

**Comment by gvoskuilen** [comment]
@jjwilke This is targeted to the master branch, can you reopen for devel?

**Comment by jjwilke** [comment]
Oops.  Now on devel.

**Pull request merged**
