### PR TITLE
Allow generic debug flags

### PR DESCRIPTION
**Pull request by berquist**
Fixes https://github.com/sstsimulator/sst-elements/issues/1558

### CODE REVIEW

**Comment by berquist** [comment]
Something is going on in the cmake-format action even though I pinned the version :(

**Comment by berquist** [comment]
> Something completely unrelated is going on in the cmake-format action even though I pinned the version :(

The fix to GHA requires https://github.com/puneetmatharu/cmake-format-lint-action/pull/6 and then bumping the action version.

**Comment by berquist** [comment]
https://github.com/puneetmatharu/cmake-format-lint-action/pull/6 is merged; I need to bump the action version then rebase this PR.

**Comment by berquist** [comment]
Explanation of what this does:

`SST_EXPORT_*FLAGS` are so that elements can be build with the same relevant `CFLAGS` and `CXXFLAGS` as core. For debugging, previously only you could compile with `-g` and have that passed on properly. If you compiled with `-g3` or `-ggdb`, core would compile fine, but `SST_EXPORT_*FLAGS` would get mangled and elements wouldn't compile.  This fixes the regex to stop this mangling and also isolates it in a function so it doesn't appear more than once.

**Review by feldergast — APPROVED** [review]

**Pull request merged**
