### PR TITLE
Add coordinates to Python API

### PR DESCRIPTION
**Pull request by bjmoor**
Allow Python API to specify coordinates for Components.  HDF5 StatOutput will record these.

### CODE REVIEW

**Comment by bjmoor** [comment]
This code expects a 1-, 2-, or 3-D set of coordinates.   I'm not opposed to a higher-dimensional set of coordinates, however, do visualization engines typically allow for that?   I'm really only familiar with up to 3D visualizations.  I understand that higher-order networks have logically higher numbers of dimensions, but in meat-space, they still are no more than 3 dimensional.

**Comment by nmhamster** [comment]
@bjmoor would it be bad to implement today as an array of coordinates so we have some flexibility on 2D vs. 3D vs. higher dimensionality stuff in the future, but just use 3D for viz right now?

**Comment by bjmoor** [comment]
I'd actually prefer to rename "Coordinates" to "VizCoords" or something like that, rather than to make it an unbounded array.  The rationale for adding this is explicitly for visualization.   Could a concept of generic coordinates be useful elsewhere?  Probably.   However, I feel that there is the potential for significant semantic confusion if we have an un-bounded array "coordinates", and other times, we implicitly declare that `coordinates[0]` is an X-dimension, `coordinates[1]` is a Y-dimension, etc.

**Comment by bjmoor** [comment]
I went ahead and made coordinates a vector, of a minimum length of 3.  If you supply less than 3 elements, it will populate out to the 3rd index with zeros.   @nmhamster , please review again.

**Pull request merged**
