### PR TITLE
Fix compiler error when calling addDataNTimes

### PR DESCRIPTION
**Pull request by stkaplan**
I get a compiler error when trying to call `addDataNTimes` from anywhere:

```
In file included from /opt/sst/include/sst/core/baseComponent.h:23,
                 from /opt/sst/include/sst/core/component.h:15,
                 from ../../../../../src/sst/elements/memHierarchy/cacheController.h:26,
                 from ../../../../../src/sst/elements/memHierarchy/cacheController.cc:21:
/opt/sst/include/sst/core/statapi/statbase.h: In instantiation of 'void SST::Statistics::Statistic<T>::addDataNTimes(uint64_t, InArgs&& ...) [with InArgs = {int}; T = long unsigned int; uint64_t = long unsigned int]':
../../../../../src/sst/elements/memHierarchy/cacheController.cc:207:37:   required from here
/opt/sst/include/sst/core/statapi/statbase.h:392:32: error: 'addData_impl_Ntimes' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  392 |             addData_impl_Ntimes(N, std::forward<InArgs>(args)...);
      |             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/sst/include/sst/core/statapi/statbase.h:392:32: note: declarations in dependent base 'SST::Statistics::StatisticCollector<long unsigned int, true>' are not found by unqualified lookup
/opt/sst/include/sst/core/statapi/statbase.h:392:32: note: use 'this->addData_impl_Ntimes' instead
```

 I don't really understand the message (hooray C++) but this is the suggested fix, and it works.

### CODE REVIEW

**Comment by stkaplan** [comment]
Not sure what's up with the cmake-format check. The log shows:

```
CRITICAL __main__.py:635: Desired config file does not exist: experimental/.cmake-format.yaml
```

Is this a bad configuration, or did I do something wrong? Running `cmake-format-test.sh` locally gives a ton of errors unrelated to my one-line change.

**Comment by stkaplan** [comment]
Never mind, I was using an outdated `devel` branch. Fixed it.

**Comment by gvoskuilen** [comment]
@stkaplan Looks like we missed adding a using statement when we added that function. In the interest of code consistency, could you instead fix it by adding a line at 371 that mirrors the line at 370 but for `addData_impl_Ntimes` instead of `addData_impl`? i.e., `using StatisticCollector<T>::addData_impl_Ntimes;` Thanks!

**Review by gvoskuilen — APPROVED** [review]
Thanks!

**Comment by stkaplan** [comment]
> @stkaplan Looks like we missed adding a using statement when we added that function. In the interest of code consistency, could you instead fix it by adding a line at 371 that mirrors the line at 370 but for `addData_impl_Ntimes` instead of `addData_impl`? i.e., `using StatisticCollector<T>::addData_impl_Ntimes;` Thanks!

Ah, didn't see that's why it works for `addData_impl` but not `addData_impl_Ntimes`. Fixed it to add the `using` statement.

**Comment by gvoskuilen** [comment]
@stkaplan The failures are a transient machine issue not caused by this PR. We'll rerun.

**Pull request merged**
